//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoHelp.DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcoHelpEntities : DbContext
    {
        public EcoHelpEntities()
            : base("name=EcoHelpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessName> BusinessNames { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Cause> Causes { get; set; }
        public virtual DbSet<CauseSolution> CauseSolutions { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Developer> Developers { get; set; }
        public virtual DbSet<IssueCause> IssueCauses { get; set; }
        public virtual DbSet<Issue> Issues { get; set; }
        public virtual DbSet<Solution> Solutions { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<SupportTechnician> SupportTechnicians { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
    }
}
