//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoHelp.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueCause
    {
        public int IssueCauseId { get; set; }
        public int IssueId { get; set; }
        public int CauseId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public int Sequence { get; set; }
    
        public virtual Cause Cause { get; set; }
        public virtual Issue Issue { get; set; }
    }
}
