//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoHelp.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public int StationId { get; set; }
        public int ZoneId { get; set; }
        public int SupervisorContactId { get; set; }
        public int StationContactId { get; set; }
        public int BusinessNameId { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual BusinessName BusinessName { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Contact Contact1 { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
